In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Load data
insurance_data = pd.read_csv("../data/insurance_claims_raw.csv")
insurance_data.head()

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,_c39
0,328,48.0,521585,2014-10-17,OH,250/500,1000.0,1406.91,0,466132,...,YES,71610.0,6510.0,13020.0,52080,Saab,92x,2004,Y,NaN
1,228,42.0,342868,2006-06-27,IN,250/500,2000.0,1197.22,5000000,468176,...,?,5070.0,780.0,780.0,3510,Mercedes,E400,2007,Y,NaN
2,134,29.0,687698,2000-09-06,OH,100/300,2000.0,1413.14,5000000,430632,...,NO,34650.0,7700.0,3850.0,23100,Dodge,RAM,2007,N,NaN
3,256,41.0,227811,1990-05-25,IL,250/500,2000.0,1415.74,6000000,608117,...,NO,63400.0,6340.0,6340.0,50720,Chevrolet,Tahoe,2014,Y,NaN
4,228,44.0,367455,2014-06-06,IL,500/1000,1000.0,1583.91,6000000,610706,...,NO,6500.0,1300.0,650.0,4550,Accura,RSX,2009,N,NaN

In [4]:
# getting the columns of the dataset
columns = list(insurance_data.columns)
columns

['months_as_customer',
 'age',
 'policy_number',
 'policy_bind_date',
 'policy_state',
 'policy_csl',
 'policy_deductable',
 'policy_annual_premium',
 'umbrella_limit',
 'insured_zip',
 'insured_sex',
 'insured_education_level',
 'insured_occupation',
 'insured_hobbies',
 'insured_relationship',
 'capital-gains',
 'capital-loss',
 'incident_date',
 'incident_type',
 'collision_type',
 'incident_severity',
 'authorities_contacted',
 'incident_state',
 'incident_city',
 'incident_location',
 'incident_hour_of_the_day',
 'number_of_vehicles_involved',
 'property_damage',
 'bodily_injuries',
 'witnesses',
 'police_report_available',
 'total_claim_amount',
 'injury_claim',
 'property_claim',
 'vehicle_claim',
 'auto_make',
 'auto_model',
 'auto_year',
 'fraud_reported',
 '_c39']

In [5]:
# # issues to note
# 1. policy_csl: has /
# 2. age: 3 missing
# 3. policy_deductable: 4 missing
# 4. policy_annual_premium: 3 missing
# 5. insured_education_level: 1 missing
# 6. insured_hobbies: 2 missing
# 7. capital-gains: 2 missing
# 8. collision_type: 178 with ?
# 9. authorities_contacted: 2 missing -> (None)
# 10.incident_state: 2 missing
# 11.incident_location: numbers + words
# 12.property_damage: 360 with ?
# 13.police_report_available: 343 with ?
# 14.total_claim_amount: 4 missing
# 15.injury_claim: 1 missing
# 16.property_claim: 1 missing
# 17._c39: NULLS

In [6]:
# examining missing values
print("Missing values distribution: ")
print(insurance_data.isnull().mean())
print("")

Missing values distribution:
months_as_customer             0.000
age                            0.002
policy_number                  0.000
policy_bind_date               0.000
policy_state                   0.000
policy_csl                     0.000
policy_deductable              0.002
policy_annual_premium          0.003
umbrella_limit                 0.000
insured_zip                    0.000
insured_sex                    0.000
insured_education_level        0.001
insured_occupation             0.000
insured_hobbies                0.002
insured_relationship           0.000
capital-gains                  0.002
capital-loss                   0.000
incident_date                  0.000
incident_type                  0.000
collision_type                 0.000
incident_severity              0.000
authorities_contacted          0.093
incident_state                 0.002
incident_city                  0.000
incident_location              0.000
incident_hour_of_the_day       0.000
number_of_vehicles_involved    0.000
property_damage                0.000
bodily_injuries                0.000
witnesses                      0.000
police_report_available        0.000
total_claim_amount             0.004
injury_claim                   0.001
property_claim                 0.001
vehicle_claim                  0.000
auto_make                      0.000
auto_model                     0.000
auto_year                      0.000
fraud_reported                 0.000
_c39                           1.000
dtype: float64

In [17]:
print("Column datatypes: ")
print(insurance_data.dtypes)

Column datatypes:
months_as_customer              int64
age                            object
policy_number                   int64
policy_bind_date               object
policy_state                   object
policy_csl                     object
policy_deductable              object
policy_annual_premium          object
umbrella_limit                  int64
insured_zip                     int64
insured_sex                    object
insured_education_level        object
insured_occupation             object
insured_hobbies                object
insured_relationship           object
capital-gains                  object
capital-loss                    int64
incident_date                  object
incident_type                  object
collision_type                 object
incident_severity              object
authorities_contacted          object
incident_state                 object
incident_city                  object
incident_location              object
incident_hour_of_the_day        int64
number_of_vehicles_involved     int64
property_damage                object
bodily_injuries                 int64
witnesses                       int64
police_report_available        object
total_claim_amount             object
injury_claim                   object
property_claim                 object
vehicle_claim                   int64
auto_make                      object
auto_model                     object
auto_year                       int64
fraud_reported                 object
dtype: object

In [18]:
# names of the columns
columns = ['age', 'policy_deductable', 'policy_annual_premium', 
           'insured_education_level', 'insured_hobbies', 
           'capital-gains', 'authorities_contacted', 
           'incident_state', 'total_claim_amount', 
           'injury_claim', 'property_claim', 
           'police_report_available']

# looping through the columns to fill the entries with NaN values with "" or 0
for column in columns:
    if column == 'age' or 'capital-gains' or 'policy_annual_premium' or 'policy_deductable' or 'police_report_available' or 'total_claim_amount' or 'total_claim_amount' or 'property_claim':
        insurance_data[column] = insurance_data[column].fillna(0)
    else:
        insurance_data[column] = insurance_data[column].fillna("")

In [14]:
# drop column with all null
insurance_data = insurance_data.drop('_c39', axis=1)